# Generated by Django 3.2.3 on 2021-06-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_auto_20210602_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('position_x', models.FloatField(blank=True, max_length=255, null=True)),
                ('position_y', models.FloatField(blank=True, max_length=255, null=True)),
                ('position_z', models.FloatField(blank=True, max_length=255, null=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='faces.face')),
            ],
        ),
    ]
