# Generated by Django 3.2.4 on 2021-06-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_with_face_bound_src',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
